### ISSUE TITLE
Simple Installation error

### ISSUE THREAD

**Issue by ccsouthard** [jenius/roots#587]
My purpose of the site is basically to explore the additional functions of axis, nib and jeet. 

So a _very_ lightweight purpose however I'd like to replace using this particular application : https://prepros.io/

1.

```
Muthership:projects chaz$ mkdir portfolio-roots
Muthership:projects chaz$ cd portfolio-roots
Muthership:portfolio-roots chaz$ sudo npm i roots@pre -g
```

no errors

2.

```
npm install sprout -g

```

no errors
3.

```
Muthership:portfolio-roots chaz$ roots new portfolio-test
✘ Error: Command failed: npm ERR! install Couldn't read dependencies
npm ERR! Error: Invalid name: "<%= name %>"
npm ERR!     at ensureValidName (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:315:15)
npm ERR!     at Object.module.exports.fixNameField (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:204:5)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:30:38
npm ERR!     at Array.forEach (native)
npm ERR!     at normalize (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:15)
npm ERR!     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:342:33)
npm ERR!     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:126:33)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:331:40
npm ERR!     at evalmachine.<anonymous>:271:14
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/chaz/.config/sprout/roots-base
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/chaz/.config/sprout/roots-base/npm-debug.log
npm ERR! not ok code 0

Potentially unhandled rejection [3] Error: Command failed: npm ERR! install Couldn't read dependencies
npm ERR! Error: Invalid name: "<%= name %>"
npm ERR!     at ensureValidName (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:315:15)
npm ERR!     at Object.module.exports.fixNameField (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:204:5)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:30:38
npm ERR!     at Array.forEach (native)
npm ERR!     at normalize (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:15)
npm ERR!     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:342:33)
npm ERR!     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:126:33)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:331:40
npm ERR!     at evalmachine.<anonymous>:271:14
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/chaz/.config/sprout/roots-base
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/chaz/.config/sprout/roots-base/npm-debug.log
npm ERR! not ok code 0

  at ChildProcess.exithandler (child_process.js:648:15)
  at ChildProcess.emit (events.js:98:17)
  at maybeClose (child_process.js:756:16)
  at Socket.<anonymous> (child_process.js:969:11)
  at Socket.emit (events.js:95:17)
  at Pipe.close (net.js:465:12)

```

Anything obvious?

**Comment by ccsouthard** [comment]
@jenius It was a permissions error.  My new stumbling block is related to dependencies and I'll search the issues to see if others have had the same problem.

 However, to tie up loose ends. What I needed to do is to change the ownership from the root to my username. To do this I used these commands:

`Muthership:/ chaz$ sudo chown -R chaz /usr/local/bin/
Muthership:/ chaz$ sudo chown -R chaz /usr/local/lib/node_modules
Muthership:/ chaz$ sudo chown -R chaz /usr/local/share/
`

**Comment by jenius** [comment]
Seems about right to me! Glad it worked out! We can talk about the next issue tomorrow :grinning:

**Comment by ccsouthard** [comment]
@jenius Got it using the patch above.
