### ISSUE TITLE
Roots new project causes "Error: Invalid name: "[object, Object]"" from normalize

### ISSUE THREAD

**Issue by gadern** [jenius/roots#623]
A new roots installation v3, I noticed during installation it had trouble with fsevents, not sure if that's related.

Any help would be much appreciated. Thanks.

```
npm ERR! install Couldn't read dependencies
✘ Error: Invalid name: "[object Object]"
Potentially unhandled rejection [3] Error: Invalid name: "[object Object]"
  at ensureValidName (/home/keith/.nvm/v0.10.33/lib/node_modules/roots/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:322:15)
  at Object.module.exports.fixNameField (/home/keith/.nvm/v0.10.33/lib/node_modules/roots/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:211:5)
  at /home/keith/.nvm/v0.10.33/lib/node_modules/roots/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:30:38
  at Array.forEach (native)
  at normalize (/home/keith/.nvm/v0.10.33/lib/node_modules/roots/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:29:15)
  at final (/home/keith/.nvm/v0.10.33/lib/node_modules/roots/node_modules/npm/node_modules/read-package-json/read-json.js:368:33)
  at then (/home/keith/.nvm/v0.10.33/lib/node_modules/roots/node_modules/npm/node_modules/read-package-json/read-json.js:127:33)
  at /home/keith/.nvm/v0.10.33/lib/node_modules/roots/node_modules/npm/node_modules/read-package-json/read-json.js:267:40
  at evalmachine.<anonymous>:271:14
  at /home/keith/.nvm/v0.10.33/lib/node_modules/roots/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
  at Object.oncomplete (evalmachine.<anonymous>:107:15)
```

**Comment by thiagodebastos** [comment]
I started getting this same issue just now.

```shell
 ❯ roots new wp-testing                          [19:57:33]
? Your project's name: wp-testing
? A brief description of your project: wp integration
▸ project created
▸ dependencies installing
npm ERR! install Couldn't read dependencies
✘ Error: Invalid name: "[object Object]"
Potentially unhandled rejection [3] Error: Invalid name: "[object Object]"
  at ensureValidName (/usr/local/lib/node_modules/roots/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:322:15)
  at Object.module.exports.fixNameField (/usr/local/lib/node_modules/roots/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:211:5)
  at /usr/local/lib/node_modules/roots/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:30:38
  at Array.forEach (native)
  at normalize (/usr/local/lib/node_modules/roots/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:29:15)
  at final (/usr/local/lib/node_modules/roots/node_modules/npm/node_modules/read-package-json/read-json.js:368:33)
  at then (/usr/local/lib/node_modules/roots/node_modules/npm/node_modules/read-package-json/read-json.js:127:33)
  at /usr/local/lib/node_modules/roots/node_modules/npm/node_modules/read-package-json/read-json.js:267:40
  at evalmachine.<anonymous>:336:14
  at /usr/local/lib/node_modules/roots/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
  at FSReqWrap.oncomplete (evalmachine.<anonymous>:99:15)


```

**Comment by hhsnopek** [comment]
I got around this by pulling the latest from master, install it (`npm install`), then linking it (`npm link`).

**Comment by gadern** [comment]
Thanks @hhsnopek, should have thought of that, common sense strikes again. Also, ```npm install -g git+https://github.com/jenius/roots.git``` worked for me if anyone is still having trouble.

**Comment by hhsnopek** [comment]
Hey everyone (@gadern & @thiagodebastos), the problem has been resolved. Run `roots tpl rest` and you'll be able to create new projects :smile:

**Comment by thiagodebastos** [comment]
Great news! thank you :dancer:

**Comment by jenius** [comment]
Hi guys! Sorry for this oversight, everything should be cleaned up and working now so I'm going to close this out :grinning:
