### ISSUE TITLE
'EMFILE' when running 'roots watch'

### ISSUE THREAD

**Issue by skibz** [jenius/roots#639]
i'm running os x yosemite and `ulimit` returns `unlimited`.

npm debug trace: 
```bash
~/github/passmark-web • roots watch
compiling...
fs.js:438
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: EMFILE, too many open files '/usr/local/lib/node_modules/roots/node_modules/readdirp/stream-api.js'
  at Object.fs.openSync (fs.js:438:18)
  at Object.fs.readFileSync (fs.js:289:15)
  at Object.Module._extensions..js (module.js:473:44)
  at Module.load (/usr/local/lib/node_modules/roots/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at readdir (/usr/local/lib/node_modules/roots/node_modules/readdirp/readdirp.js:52:25)
  at EventEmitter.<anonymous> (/usr/local/lib/node_modules/roots/node_modules/chokidar/lib/fsevents-handler.js:309:7)
  at Object.oncomplete (fs.js:107:15)
```

some further context to my situation: i'm attempting to compile a static site that uses `roots-records`. before running the `roots watch` step, i use `gulp` to pull down some external data. the external data is written to a file in the project's root directory. this json file is then `require`d  into the `app.coffee` file for use with `roots-records`. the json file is more or less 20mb in size. could it be that the json file is too large?

**Comment by declandewet** [comment]
You can point `roots-records` directly at the data file, rather than `require`ing it - try something like this:

```coffee
extensions: [
  records({
    shoes: {file: 'data/books.json'}
  })
]
```

That might work. I don't think the JSON file being too large is an issue as I've used extremely large (80mb+) files for projects with multiple translations
