### ISSUE TITLE
Roots 4.0.0 won't deploy -to gh-pages

### ISSUE THREAD

**Issue by eliwilliamson** [jenius/roots#700]
hangs and returns the following error

`{ [Error: read ETIMEDOUT]
  defaultMessage: 'Internal Server Error',
  message: 'read ETIMEDOUT',
  code: '500' }
Potentially unhandled rejection [6] read ETIMEDOUT
  at Object.proto.sendError (/usr/local/lib/node_modules/roots/node_modules/ship/node_modules/github/api/v3.0.0/index.js:30:19)
  at /usr/local/lib/node_modules/roots/node_modules/ship/node_modules/github/api/v3.0.0/gitdata.js:83:29
  at ClientRequest.<anonymous> (/usr/local/lib/node_modules/roots/node_modules/ship/node_modules/github/index.js:786:17)
  at emitOne (events.js:77:13)
  at ClientRequest.emit (events.js:169:7)
  at TLSSocket.socketErrorListener (_http_client.js:259:9)
  at emitOne (events.js:77:13)
  at TLSSocket.emit (events.js:169:7)
  at emitErrorNT (net.js:1253:8)
  at doNTCallback2 (node.js:441:9)
  at process._tickCallback (node.js:355:17)`

No issues in my app.coffee file as far as i can tell

`axis            = require 'axis'
rupture         = require 'rupture'
sass            = require 'node-sass'
autoprefixer    = require 'autoprefixer-stylus'
js_pipeline     = require 'js-pipeline'
css_pipeline    = require 'css-pipeline'

module.exports =
  ignores: ['readme.md', '**/layout.*', '**/_*', '.gitignore', 'ship.*conf']

  extensions: [
    js_pipeline(files: 'assets/js/*.js'),
    css_pipeline(files: 'assets/css/*.scss')
  ]

  stylus:
    use: [axis(), rupture(), autoprefixer()]
    sourcemap: true

  'coffee-script':
    sourcemap: true

  jade:
    pretty: true
`

**Comment by FranzSkuffka** [comment]
hint: @eliwilliamson you can enclose your code blocks inside ``` to format them accordingly.

**Comment by eliwilliamson** [comment]
thank you @FranzSkuffka :+1:

**Comment by jenius** [comment]
Hey, sorry about this! It seems like ship may have fallen behind with the github api recently, perhaps. I'll look into this soon.

**Comment by eliwilliamson** [comment]
thank you @jenius - please let me know when this is resolved as i have a few projects utilizing roots at the moment. thanks again for all your (and carrot creative's) hard work!

**Comment by newswim** [comment]
I talked to someone at Github recently, and confirmed that there have been some changes regarding the rate and file size of deployments. Being that Ship pushes up the entire directory, projects deploying to gh-pages will need to keep a careful eye on the size of their projects.

Hopefully, a future version might see some diffing going on so that only changes to files get pushed. Until then, I just have to be really careful about the size of my assets.

In the mean time, you can always use something like Netlify, which doesn't have a strict of restrictions (and still lets you deploy stuff for free).

**Comment by jenius** [comment]
Thanks for the update @newswim - good info. I think what you are saying about only pushing changed assets is probably the best solution. But this would be a pretty difficult implementation, and unfortunately I don't see my company allocating time towards working on this, since we just use netlify. I'd be happy to work with someone on a PR to implement this type of thing though!

**Comment by eliwilliamson** [comment]
Thank you for the update @newswim i'm excited to see this feature enhancement. In the mean time, @jenius is there a way to optimize the `compile` command to work out of the box with netlify? I tried to deploy a site (and compile locally for that matter) with multiple layouts and it left me with a broken build. On netlify, I received the following error: `Error: Error running command: Build script returned non-zero exit code: 127` (see my settings on netlify attached below). I used to love the out-of-the-box functionality of roots and github - the "it just works" bit really made me an advocate. I hope carrot see's this enhancement as an investment in retaining the usership who were attracted to roots for the same reason.
![screen shot 2016-02-22 at 3 00 06 pm](https://cloud.githubusercontent.com/assets/871660/13232501/0177b0fa-d975-11e5-888d-78f0b87a0bd2.png)

**Comment by jenius** [comment]
Netlify works with roots out of the box as well. Do you have roots as a dependency in your `package.json` file? You'll need it there for netlify to know which version you're after and to have it installed for the compile.

**Comment by eliwilliamson** [comment]
that was it @jenius - thanks for the help and hope to see gh-pages working again soon with a Ship project update :+1:
